apiVersion: apps.rector.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: default
spec:
  image: nginx:1.25-alpine
  replicas: 2
  port: 80
  serviceType: ClusterIP
  serviceAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
  env:
    - name: ENV
      value: production
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-app-secrets
          key: db-password
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
  tolerations:
    - key: dedicated
      operator: Equal
      value: my-app
      effect: NoSchedule
